org.gradle.jvmargs=-Xmx1G

loom.platform=neoforge

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
yarn_patch=1.21+build.4
neoforge_version=21.4.59-beta

mod_version = 0.1.1
maven_group = org.thinkingstudio
archives_base_name = AnimaticaFoxified

curseforge_id=1103129
modrinth_id=nrSnNUz4

sodium_version=mc1.21.4-0.6.6
