modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"

[[mods]]
modId = "animatica"
version = "${version}"
displayName = "AnimaticaFoxified"
displayURL="https://github.com/ThinkingStudios/AnimaticaFoxified" #optional
logoFile="assets/animatica/icon.png" #optional
credits="FoundationGames" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Animatica unofficial NeoForge port.

Allow for animating more game textures using the MCPatcher/OptiFine animation format.
'''

[[mixins]]
config = "animatica.mixins.json"

[[dependencies.animatica]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,20.6]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.animatica]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.20.6]"
ordering = "NONE"
side = "CLIENT"